### PR TITLE
25x25x7mm Fan cover mod

### PR DESCRIPTION
**Pull request by o1hitman1o**
This is my first ever pull request. This is a mod to the cover to add a cooling fan for the toolhead control board.

### CODE REVIEW

**Comment by o1hitman1o** [comment]
Submission for mod to add a fan to the cover for toolhead control board cooling.

**Comment by o1hitman1o** [comment]
Updated to add a mod of the umbilical mount created from Baze_24616 and hartk to add 3DO Nozzle Camera Mount but keep the same threads as hartk version.

**Comment by JaredC01** [comment]
This PR is for more than one mod, which is an issue.  Please create one pull request per mod.

Also, the cable cover door is being completely updated, so your current mod will need to be remade with the new cable cover door.

Lastly, DO NOT attach cable glands (or anything that will affect the stepper's position) to the stepper with G2E, as you will cause a number of issues to extrusion consistency since the stepper is NOT stationary with G2E.

**Comment by o1hitman1o** [comment]
@JaredC01 where would one find the updated cover?

**Pull request closed without merging**
